import React,{useEffect,useState} from "react";
import{createRoot}from"react-dom/client";
import{ArrowUpRight,Code2,Github,Linkedin,Mail,MapPin,Menu,Moon,Phone,Sun,X}from"lucide-react";
import"./styles.css";
const projects=[
{n:"01",name:"URBAN PULSE AI",kind:"Civic technology · AI",desc:"An AI-oriented civic platform concept for surfacing urban issues and helping route reports into response workflows.",stack:["TypeScript","Python","AI/ML"],url:"https://github.com/hiteshcv17/URBAN-PULSE-AI"},
{n:"02",name:"KRISHI-SAHAY",kind:"Web development · Agriculture",desc:"A web project exploring accessible digital experiences for agriculture-related use cases.",stack:["HTML","CSS","JavaScript"],url:"https://github.com/hiteshcv17/KRISHI-SAHAY"},
{n:"03",name:"DECIBAL-DRIFT",kind:"Python · Application development",desc:"A Python project built as part of an ongoing journey in practical software development and problem solving.",stack:["Python"],url:"https://github.com/hiteshcv17/DECIBAL-DRIFT"},
{n:"04",name:"CHRONO-SHIELD",kind:"Python · Application development",desc:"A Python-based project focused on turning a defined problem into a working software solution.",stack:["Python"],url:"https://github.com/hiteshcv17/CHRONO-SHIELD"}];
const skills=[["Languages","Python","Java","C"],["Web","HTML","CSS","JavaScript"],["Foundations","Data Structures & Algorithms","OOP","Problem Solving"],["Tools","Git","GitHub","VS Code"]];
function App(){const[theme,setTheme]=useState("light"),[open,setOpen]=useState(false);useEffect(()=>{document.documentElement.dataset.theme=theme},[theme]);const close=()=>setOpen(false);return <div>
<header className="topbar"><a className="brand" href="#home" onClick={close}><b>HC<span>.</span></b><strong>HITESH C V</strong></a><button className="mobile" aria-label="Toggle navigation" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button><nav className={open?"nav show":"nav"}><a href="#about" onClick={close}>About</a><a href="#projects" onClick={close}>Projects</a><a href="#skills" onClick={close}>Skills</a><a href="#journey" onClick={close}>Journey</a><a href="#contact" onClick={close}>Contact</a><button className="mode" onClick={()=>setTheme(theme==="light"?"dark":"light")}>{theme==="light"?<Moon size={16}/>:<Sun size={16}/>} {theme==="light"?"Dark":"Light"} mode</button></nav></header>
<main>
<section className="hero wrap" id="home"><div className="hero-copy"><p className="kicker"><i/> COMPUTER SCIENCE · MYSURU, INDIA</p><h1>Building things.<br/><em>Learning by doing.</em></h1><p className="intro">I’m Hitesh — a Computer Science Engineering student interested in software development, problem solving, and turning ideas into useful digital experiences.</p><div className="actions"><a className="button" href="#projects">Explore my work <ArrowUpRight size={17}/></a><a className="simple-link" href="https://github.com/hiteshcv17" target="_blank" rel="noreferrer">GitHub profile <ArrowUpRight size={16}/></a></div><div className="meta"><span><MapPin size={15}/> Mysuru, Karnataka</span><span><Code2 size={15}/> Learning Java & DSA</span></div></div><aside className="note"><div className="note-top"><span>FIELD NOTES / 001</span><span>2026—</span></div><div className="monogram">HC<span>.</span></div><p className="tiny">A LITTLE ABOUT MY APPROACH</p><p className="quote">“Stay curious. Build something. Learn what breaks.”</p><div className="note-bottom">STUDENT DEVELOPER <span>/{'{}'}</span></div><div className="stamp">OPEN<br/>TO<br/>LEARN</div></aside><div className="index">01 <span>—</span> INTRODUCTION</div></section>
<section className="about band" id="about"><div className="wrap two-col"><div><p className="kicker">01 / ABOUT</p><h2>Curiosity is the<br/><em>starting point.</em></h2></div><div className="body-copy"><p>I’m studying Information Science and Engineering at Maharaja Institute of Technology Mysore. I enjoy learning how software works from the fundamentals up, then applying that knowledge through projects, experiments, and team challenges.</p><p>I’m still early in my journey, so I value clear thinking, steady practice, and honest iteration more than buzzwords. Each project is a chance to learn something I can carry into the next one.</p><a className="simple-link" href="https://www.linkedin.com/in/hitesh-cv-ab48b4335" target="_blank" rel="noreferrer">Connect on LinkedIn <ArrowUpRight size={16}/></a></div></div></section>
<section className="wrap projects" id="projects"><div className="heading"><div><p className="kicker">02 / SELECTED WORK</p><h2>Projects with a <em>purpose.</em></h2></div><a className="simple-link" href="https://github.com/hiteshcv17?tab=repositories" target="_blank" rel="noreferrer">All repositories <ArrowUpRight size={16}/></a></div><div className="project-list">{projects.map(p=><article className="project" key={p.n}><span className="num">{p.n}</span><div><p className="kind">{p.kind}</p><h3>{p.name}</h3><p className="desc">{p.desc}</p><div className="tags">{p.stack.map(s=><span key={s}>{s}</span>)}</div></div><a className="project-arrow" href={p.url} target="_blank" rel="noreferrer" aria-label={"Open "+p.name+" repository"}><ArrowUpRight size={20}/></a></article>)}</div><p className="disclaimer">Before publishing, verify each project summary against the repository README and replace any broad description with its actual features.</p></section>
<section className="band" id="skills"><div className="wrap skills"><div className="heading"><div><p className="kicker">03 / TOOLKIT</p><h2>Tools I’m <em>working with.</em></h2></div><p className="side-note">A growing toolkit — not a finished list.</p></div><div className="skill-grid">{skills.map((s,i)=><article className="skill" key={s[0]}><span className="num">0{i+1}</span><h3>{s[0]}</h3><div className="tags">{s.slice(1).map(t=><span key={t}>{t}</span>)}</div></article>)}</div></div></section>
<section className="wrap journey" id="journey"><p className="kicker">04 / MILESTONES</p><h2>Learning in <em>public.</em></h2><div className="timeline"><article><time>JUN 2026</time><div><h3>Runner-Up · IDEATHON 2026 — ThinkTank</h3><p>Maharaja Institute of Technology Mysore.</p></div></article><article><time>MAY 2026</time><div><h3>Participant · FusionX 1.0 Hackathon</h3><p>IEEE Bangalore Section and IEEE Industry Applications Society.</p></div></article><article><time>APR 2026</time><div><h3>Participant · HACK-OLYMPIC 2026</h3><p>24-hour national-level hackathon at JSS Science and Technology University, Mysuru.</p></div></article><article><time>AUG 2028</time><div><h3>B.E. · Information Science and Engineering</h3><p>Maharaja Institute of Technology Mysore · Expected graduation.</p></div></article></div></section>
<section className="contact"><div className="wrap contact-grid" id="contact"><div><p className="kicker">05 / SAY HELLO</p><h2>Good work starts<br/>with a <em>conversation.</em></h2><p className="contact-copy">Interested in a project, an idea, or a chance to learn together? Feel free to reach out.</p></div><div className="contact-list"><a href="mailto:hiteshcv507@gmail.com"><Mail/><span><small>EMAIL</small>hiteshcv507@gmail.com</span><ArrowUpRight/></a><a href="https://github.com/hiteshcv17" target="_blank" rel="noreferrer"><Github/><span><small>GITHUB</small>github.com/hiteshcv17</span><ArrowUpRight/></a><a href="https://www.linkedin.com/in/hitesh-cv-ab48b4335" target="_blank" rel="noreferrer"><Linkedin/><span><small>LINKEDIN</small>Connect professionally</span><ArrowUpRight/></a><a href="tel:+917337846678"><Phone/><span><small>PHONE</small>+91 73378 46678</span><ArrowUpRight/></a></div></div></section>
</main><footer className="wrap footer"><a className="brand" href="#home"><b>HC<span>.</span></b><strong>HITESH C V</strong></a><p>Made with care, curiosity, and a lot of learning.</p><a href="#home">Back to top <ArrowUpRight size={15}/></a><small>© {new Date().getFullYear()}</small></footer></div>}
createRoot(document.getElementById("root")).render(<App/>);